openapi: 3.1.0
info:
  title: poster-api
  description: API pour la gestion d'affiches (posters).
  version: 1.0.0

servers:
  - url: https://api.posters.com/v1
    description: Serveur de production

paths:
  /posters:
    get:
      summary: Lister toutes les affiches
      description: Renvoie une liste de toutes les affiches.
      responses:
        '200':
          description: Une liste d'affiches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Poster'
        default:
          description: Erreur inattendue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Ajouter une nouvelle affiche
      description: Ajoute une nouvelle affiche à la liste.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poster'
      responses:
        '201':
          description: Affiche créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poster'
        '400':
          description: Données de requête invalides
        default:
          description: Erreur inattendue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /posters/{id}:
    get:
      summary: Trouver une affiche par ID
      description: Renvoie une seule affiche identifiée par son ID.
      parameters:
        - name: id
          in: path
          required: true
          description: L'identifiant unique de l'affiche.
          schema:
            type: integer
      responses:
        '200':
          description: Détails de l'affiche
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poster'
        '404':
          description: Affiche non trouvée
        default:
          description: Erreur inattendue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Mettre à jour une affiche
      description: Met à jour les informations d'une affiche existante.
      parameters:
        - name: id
          in: path
          required: true
          description: L'identifiant unique de l'affiche à mettre à jour.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poster'
      responses:
        '200':
          description: Affiche mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poster'
        '404':
          description: Affiche non trouvée
        '400':
          description: Données de requête invalides
        default:
          description: Erreur inattendue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Supprimer une affiche
      description: Supprime une affiche spécifique de la liste.
      parameters:
        - name: id
          in: path
          required: true
          description: L'identifiant unique de l'affiche à supprimer.
          schema:
            type: integer
      responses:
        '204':
          description: Affiche supprimée avec succès (aucun contenu)
        '404':
          description: Affiche non trouvée
        default:
          description: Erreur inattendue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Poster:
      type: object
      required:
        - imageUrl
      properties:
        id:
          type: integer
          description: Identifiant unique de l'affiche.
          readOnly: true
        imageUrl:
          type: string
          description: L'URL de l'image de l'affiche.
          examples:
            - "https://images.posters.com/posters/poster1.jpg"
        title:
          type: string
          description: Le titre ou la description de l'affiche.
          examples:
            - "Affiche"
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
