openapi: 3.1.0
info:
  title: authentification-api
  description: API for user authentication and authorization.
  version: 1.0.0

servers:
  - url: https://api.authentification.com/v1
    description: Production server

paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request data
        '409':
          description: User already exists
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      summary: User login
      description: Authenticates a user and returns an access token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
        '400':
          description: Invalid request data
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      summary: User logout
      description: Invalidates the current user session.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
        '401':
          description: Unauthorized
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/me:
    get:
      summary: Get current user
      description: Returns the authenticated user's information.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{id}:
    get:
      summary: Find a user by ID
      description: Returns a single user identified by its ID.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the user.
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '401':
          description: Unauthorized
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a user
      description: Updates the information of an existing user.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the user to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '401':
          description: Unauthorized
        '400':
          description: Invalid request data
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a user
      description: Deletes a specific user account.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the user to delete.
          schema:
            type: integer
      responses:
        '204':
          description: User deleted successfully (No content)
        '404':
          description: User not found
        '401':
          description: Unauthorized
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
        - username
      properties:
        email:
          type: string
          format: email
          description: User's email address.
          examples:
            - "user@example.com"
        password:
          type: string
          format: password
          description: User's password.
          examples:
            - "password"
        username:
          type: string
          description: User's username.
          examples:
            - "levy marques"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address.
          examples:
            - "user@example.com"
        password:
          type: string
          format: password
          description: User's password.
          examples:
            - "password"

    RefreshTokenRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          description: The refresh token.
          examples:
            - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token.
          examples:
            - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        refreshToken:
          type: string
          description: JWT refresh token.
          examples:
            - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        expiresIn:
          type: integer
          description: Token expiration time in seconds.
          examples:
            - 3600
        tokenType:
          type: string
          description: Type of the token.
          examples:
            - "Bearer"

    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the user.
          readOnly: true
          examples:
            - 1
        email:
          type: string
          format: email
          description: User's email address.
          examples:
            - "user@example.com"
        username:
          type: string
          description: User's username.
          examples:
            - "levy marques"
        createdAt:
          type: string
          format: date-time
          description: Account creation date.
          examples:
            - "2026-01-27"

    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: User's email address.
          examples:
            - "newemail@example.com"
        username:
          type: string
          description: User's username.
          examples:
            - "newusername"
        password:
          type: string
          format: password
          description: New password.
          examples:
            - "password"

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
